---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openspeedtest
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: openspeedtest
  replicas: 1
  template:
    metadata:
      labels:
        app: openspeedtest
    spec:
      containers:
        - name: openspeedtest
          image: openspeedtest/latest:v2.0.4
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: openspeedtest
  namespace: monitoring
  annotations:
    # Expose to tailscale
    tailscale.com/expose: "true"
    tailscale.com/hostname: "speedtest"
spec:
  ports:
    - name: web
      port: 80
      targetPort: 3000
  selector:
    app: openspeedtest
---
