apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: yak-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.5.1
      user: ubuntu
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: controller
  - ssh:
      address: 192.168.5.2
      user: ubuntu
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: worker
  - ssh:
      address: 192.168.5.3
      user: ubuntu
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: worker
  - ssh:
      address: 192.168.5.4
      user: ubuntu
      port: 22
      keyPath: ~/.ssh/id_ed25519
    role: worker
  k0s:
    version: v1.29.2+k0s.0
    dynamicConfig: false
    config: {}
