---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBHfOICYfs15aGI4k09BPJstV+9pL5JggEwO/s+2ylBeSGvnyGeq38mP9/zLVDvs5LcJgSg8edtTjxXcuZBTTZ3CMHSEASYENWqOhdW2A7PODeMP68pZR5xeSbYtqIo5TF1Re6G+gjcpUb4rTYu22zHJYxlIabCU3MagPxMnnpYRa19FemUfA4tH98ZfhbSFUzuV5pdNLVYVwpMF68I6bhS7plG5QS6MaUt1lPSua8Sog8GH7l9dYyLlBCaTvx+7f8gIdhOCmhu1XzRfYhJbXADNxSCv4gXes/lRRzMF8BKXayxWx3NRTubZ9ISkRYelq9IzKvv3Mi80RRnHqJr4Hii6iGy9tH6wY4B5nkn8pb/za3M8GomzbVQCS2rqkIALdIrj20aiq+tUNNJpSxJBSDtKaNVBVd7gu//tnDF1oUA5INvjPxRtuD/2nB+XK/R6aKKV/OD2BMUVDGrzyHJ5UVNIeeRHP89haZndxrWFl4gjWdXXMAfyU1AnAje7BTXjkiQkMwLCIjYGs3ixHIyMNp0vjwr2YPuV+s+S1k5qXaN+8/W6Zgyp75P8r2XEpVMKU2sdF3llgIrJrupSzXQP2/zFFDfJH19e0HYF7ciEQK2o7TgLhkrKT18zEbaS29pfxsDoTJ9brD/H+5EldvWpU+MW63+rdWIlcPC6riytU1AjB8ORAYyA/jMTiSV1LP/4tcL4/Z37P7xUeuXLGw=
    client_secret: AgBfvwhbO5DupOMzIUXM3WQHqJY6rxOSjOaG/wAq8ToF6DqybT2icLs0fsKgcwlY3UWvJso98OdsDiJq3kcKqt6HooxMU62Fg5Xk9RKxLAugvUQVEnsT5olVpSH7oRFMnOcZNXofJj7GLeCs2RSLJ7KCwXWRnTHO8kzDQWWsugu/tQnwK+U+IE81DObmFMavLCm5wuJMGhyB0c73SMq7+dmgi+IlsYJ3PxfWiz69/vqA6ivWzZxvgp7Pebuxp7wrAvfV9kn+IQV7SeEvzfeX/ajYFVBZCCk5ZAqc/ksyxxvJpNYcR0up3P1DRhid6AiRlg9R1lLpMWhaFT0GZZ7kj59RW8PacdAxsPlmBzNblEIlk3IPswC+CW+xWRVbwuj5CHl22QCMwU1Ltfk4HJ8wGAlMdwSMTuyRHxlFGqF+1E2g9qWa78/KwgZxzL0UCoiFNrKPohfBQ5YKnrWAJyvDQJulSJ7rreKflzKg0zwr3eRA5fyj1YVQcuQVMPhKj4FyuA92LfIr5DbOvtHTTcNZt2jlKSGy0vOKOcdlS67p0Id96+8WC76cTlm/2LywjIMTctTHngRneey+4cIwsxiDGS5p4t9+0D7mPjTk95Nfpoj59xdSDjv+i8sd4BV+aqsZ2lUwZJj+zUsZl4KXZpa73k2rYQxkCuCsEkeO8WPLdjVeMyHxlCx6P1uSFiEpTQh6ELDVydGXRiZryy0y6DM2JJw9iw6YNBgCnecZPUqOGGSy5V74/0OLSxnoeJtfde3hLi6LWxcJ8OHxV5DD
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
