apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wyoming-whisper-server
  namespace: homeassistant
  labels:
    app.kubernetes.io/name: wyoming-whisper
    app.kubernetes.io/component: tts
    app.kubernetes.io/part-of: homeassistant
    app.kubernetes.io/version: "2.2.0"
spec:
  serviceName: wyoming-whisper-server
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wyoming-whisper
      app.kubernetes.io/component: tts
      app.kubernetes.io/part-of: homeassistant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wyoming-whisper
        app.kubernetes.io/component: tts
        app.kubernetes.io/part-of: homeassistant
        app.kubernetes.io/version: "2.2.0"
    spec:
      hostNetwork: true
      containers:
        - name: wyoming-whisper-server
          image: rhasspy/wyoming-whisper:2.2.0
          args: ["--model","tiny-int8", "--language", "en"]
          ports:
            - name: wyoming
              containerPort: 10300
              protocol: TCP
          volumeMounts:
            - name: wyoming-whisper-server-data
              mountPath: /data/
          resources:
            requests:
              cpu: 100m
              memory: 48Mi
            limits:
              cpu: 1000m
              memory: 1.5Gi
  volumeClaimTemplates:
    - metadata:
        name: wyoming-whisper-server-data
        namespace: homeassistant
        labels:
          app.kubernetes.io/name: wyoming-whisper
          app.kubernetes.io/component: tts
          app.kubernetes.io/part-of: homeassistant
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: wyoming-whisper-server
  namespace: homeassistant
  labels:
    app.kubernetes.io/name: wyoming-whisper
    app.kubernetes.io/component: tts
    app.kubernetes.io/part-of: homeassistant
    app.kubernetes.io/version: "2.2.0"
spec:
  ports:
    - name: wyoming
      port: 10300
      targetPort: wyoming
  selector:
    app.kubernetes.io/name: wyoming-whisper
    app.kubernetes.io/component: tts
    app.kubernetes.io/part-of: homeassistant
---
