network:
    version: 2
    ethernets:
        eth0:
            dhcp4: false
            addresses: [192.168.5.2/22]
            gateway4: 192.168.4.1
            nameservers:
                addresses: [192.168.4.1]
